### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by abepetrillo** [rubyireland/rubyjobs2#12]
Website seems to be down?

**Comment by theirishpenguin** [comment]
Yes. I've received a report of this too. Haven't had time to look into it.

**Comment by abepetrillo** [comment]
After a quick whois looks like this is hosted on aws? Looks like the EC2 instance needs a reboot :)

**Comment by theirishpenguin** [comment]
It's a heroku app I think.

**Comment by theirishpenguin** [comment]
It was a dns issue. Not sure why it just started recently. The www
subdomain is fine. The naked domain still needs tweakin'

**Comment by theirishpenguin** [comment]
This is no longer an issue.
